name: p1

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - dev
    paths:
      - ".github/**"

jobs:
  github_context:
    runs-on: ubuntu-latest
    steps:
      - name: Understand GitHub context
        run: |
          echo '{"name":"test","version":1}' | jq .
          echo '${{ toJson(github) }}' | jq .

  init_job:
    needs: github_context
    runs-on: ubuntu-24.04
    steps:
      - name: Get code
        uses: actions/checkout@v7

      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false
          check-latest: false

      - name: Confirm Node.js
        run: |
          echo "Node & NPM Version:"
          node --version
          npm --version

  first_job:
    needs: init_job
    runs-on: ubuntu-22.04
    steps:
      - name: Check OS
        run: cat /etc/os-release

      - name: Check CPU and memory
        run: |
          echo "CPU:"
          nproc
          lscpu
          echo "Memory:"
          free -m

  call_workflow_p2:
    uses: "./.github/workflows/p2.yml"
    with:
      name: "Katherine"
