name: p2
concurrency: 
  cancel-in-progress: true
  group: p2c
on:
  workflow_dispatch: 
  workflow_call:
    inputs:
      name:
        description: "Name need for running this workflow"
        default: "John Doe"
        required: false
        type: string
      code:
        description: "code input"
        default: "matlab"
        required: false
        type: string

run-name: ${{ github.actor }} triggered workflow in ${{ github.repository }} | ${{ inputs.name }}
jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print name
        run: |
          echo "Name is: ${{ inputs.name }}"
          echo "Completed"
          
  print-username:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.code }}
