name: p5

on:
  workflow_dispatch:

env:
  var1: "Some Variable 1"

jobs:
  first_job:
    uses: "./.github/workflows/p2.yml"
    with:
      name: "Katherine"
      
  second_job:  
    needs: first_job
    runs-on: ubuntu-22.04
    env:
      job_va1: "Job Var 1"
    outputs:
      out1: ${{ steps.metadata.outputs.out }}
    steps:
      - name: Global env
        run: echo ${{ env.var1 }}
      - name: Job Specific Variable
        run: echo ${{env.job_va1}}
      - name: some output
        run: echo "out=john wick" >> $GITHUB_OUTPUT
        id: metadata

  upload-artifat:
    needs: second_job
    runs-on: ubuntu-22.04

    steps:
      - run: echo 'hello world artifact text file and ${{ needs.second_job.outputs.out1 }}' > hello.txt
      - name: upload action
        uses: actions/upload-artifact@v7
        with:
          include-hidden-files: false
          name: ga_art
          path: |
            ./hello.txt
  
  download-artifacts:
    needs: upload-artifat
    runs-on: ubuntu-latest
    steps:
      - name: print file contents
        uses: actions/download-artifact@v8
        with:
          name: ga_art
          path: ./download_path

      - name: get contents
        run: |
          ls -la
          cat ./download_path/hello.txt
          sleep 5
          echo "Completed"
      
            
          
