name: p5

on:
  workflow_dispatch:

env:
  var1: "Some Variable 1"

jobs:
  first_job:
    uses: "./.github/workflows/p2.yml"
    with:
      name: "Katherine"
      
  second_job:  
    needs: first_job
    runs-on: ubuntu-22.04
    env:
      job_va1: "Job Var 1"
      
    steps:
      - name: Global env
        run: echo ${{ env.var1 }}
      - name: Job Specific Variable
        run: echo ${{env.job_va1}}

  upload-artifat:
    needs: second_job
    runs-on: ubuntu-22.04

    steps:
      - run: echo 'hello world artifact text file' > hello.txt
      - name: upload action
        uses: actions/upload-artifact@v7
        with:
          include-hidden-files: false
          name: ga_art
          path: |
            ./hello.txt
  

      
            
          
