name: Deploy after CI

on:
  workflow_run:
    workflows:
      - p1
    types:
      - completed

jobs:
  deploy:
    # Do not deploy if p1 failed.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "p1 succeeded; deploying..."
      - run: sleep 10
      - run: echo "Deployment completed."
